### PR TITLE
should reference the project site

### PR DESCRIPTION
**Pull request by AdrianRossouw**
link the logo and first instance of the name to nscale.nearform.com

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
Thanks Adrian, merging now!

Don't suppose you want to do the rest of the pages as they all have a logo. If not cool :smile:

**Comment by AdrianRossouw** [comment]
nah dude. i thought it would be a more constructive way to point it out =P

**Comment by mcdonnelldean** [comment]
@AdrianRossouw Fully appreciate that :smile: I have a guy looking to get exp pushing and pulling to repo's so this would suit him perfect! Cheers for pointing it out though, much better experience now.

**Comment by mcollina** [comment]
Thanks @AdrianRossouw! As you can see the team is growing! :)

**Pull request merged**
